[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/app/logs

[program:backend]
command=python3 main.py
directory=/app/backend
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
stdout_logfile=/app/logs/backend.log
stderr_logfile=/app/logs/backend_error.log
environment=BACKEND_PORT="8483",BACKEND_HOST="0.0.0.0",ENV="production",STATIC="/static",OUT_DIR="./static/screenshots",NOTE_OUTPUT_DIR="note_results",IMAGE_BASE_URL="/static/screenshots",DATA_DIR="data",TRANSCRIBER_TYPE="fast-whisper",WHISPER_MODEL_SIZE="base",DATABASE_URL="sqlite:///data/video_note.db"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
stdout_logfile=/app/logs/nginx.log
stderr_logfile=/app/logs/nginx_error.log